[package]
name = "TCPServer"
version = "0.1.0"
authors = ["segfo <k.segfo@gmail.com>"]

[dependencies]
crossbeam = "0.2.10"
serde = "1.0.10"
serde_json = "1.0"
serde_derive = "1.0.10"
native-tls = "0.1"
bufstream = "0.1.3"
